source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

def shared_pods
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'ObjectMapper'
end

target "WeatherDemo" do
	shared_pods
    pod 'Alamofire'
    pod 'Kingfisher'
end

target "WeatherDemoTests" do
	shared_pods 
end
